import { LegalLayout } from "../../components/LegalLayout";

export function Privacy() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="April 20, 2026">
      <h2>1. Information we collect</h2>
      <p>
        We collect information you provide directly (name, email, billing details), information
        generated by your use of the Service (usage logs, task history, agent configurations), and
        technical information automatically collected from your browser or device (IP address,
        browser type, cookies).
      </p>

      <h2>2. How we use your information</h2>
      <p>We use the information we collect to:</p>
      <ul>
        <li>Provide, operate, and improve the Foreman service;</li>
        <li>Process transactions and send related information including purchase confirmations and invoices;</li>
        <li>Send transactional and promotional communications (you may opt out of promotional messages);</li>
        <li>Monitor and analyze usage patterns to improve user experience;</li>
        <li>Detect, investigate, and prevent fraudulent transactions and other illegal activities;</li>
        <li>Comply with legal obligations.</li>
      </ul>

      <h2>3. Information sharing</h2>
      <p>
        We do not sell your personal information. We share information only with service providers
        who assist us in operating the platform (payment processors, cloud infrastructure, email
        providers), and only to the extent necessary to perform those services. We may also disclose
        information when required by law or to protect our rights.
      </p>

      <h2>4. Data retention</h2>
      <p>
        We retain your information for as long as your account is active or as needed to provide
        services. You may request deletion of your account and associated data at any time by
        contacting <a href="mailto:privacy@foreman.company">privacy@foreman.company</a>.
      </p>

      <h2>5. California privacy rights (CCPA)</h2>
      <p>
        California residents have the right to know what personal information we collect, request
        deletion of their personal information, and opt out of the sale of personal information (we
        do not sell personal information). To exercise these rights, contact{" "}
        <a href="mailto:privacy@foreman.company">privacy@foreman.company</a> or submit a request via
        our contact page. We will respond within 45 days.
      </p>
      <p>
        We do not discriminate against California residents who exercise their CCPA rights.
      </p>

      <h2>6. Cookies</h2>
      <p>
        We use cookies and similar tracking technologies. See our{" "}
        <a href="/cookies">Cookie Policy</a> for details.
      </p>

      <h2>7. Third-party AI providers</h2>
      <p>
        Foreman routes tasks through third-party AI providers (currently OpenRouter and its
        downstream model providers). Content you submit as agent instructions or task inputs may be
        processed by these providers subject to their own terms. We do not use your data to train
        models.
      </p>

      <h2>8. Security</h2>
      <p>
        We implement industry-standard security measures including encryption in transit (TLS),
        encryption at rest, and row-level security for multi-tenant data isolation. See our{" "}
        <a href="/security">Security page</a> for more detail.
      </p>

      <h2>9. Children</h2>
      <p>
        Foreman is not directed at children under 13. We do not knowingly collect personal
        information from children under 13. If you believe we have collected such information,
        contact us immediately.
      </p>

      <h2>10. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify you of material changes
        by email or by posting a notice on the Service. Your continued use after the effective date
        constitutes acceptance of the revised policy.
      </p>

      <h2>11. Contact</h2>
      <p>
        Foreman<br />
        <a href="mailto:privacy@foreman.company">privacy@foreman.company</a>
      </p>
    </LegalLayout>
  );
}
